const state = {
    id: "vpiDashboard",
    active: false,
    name: "translate#additional:modules.tools.vpiDashboard.title",
    icon: "bi-graph-up",
    renderToWindow: true,
    resizableWindow: true,
    isVisibleInMenu: true,
    deactivateGFI: false,
    frequencyData: undefined,
    chartData: "overview",
    allDataClicked: true,
    averageVisitorsPerMonth: [],
    averageVisitorsPerDay: [],
    individualVisitorsPerYear: "",
    allLocationsGeoJson: undefined,
    allLocationsArray: [],
    dwellTimeLocationA: undefined,
    dwellTimeLocationB: undefined,
    ageGroupsLocationA: undefined,
    ageGroupsLocationB: undefined,
    visitorTypesLocationA: undefined,
    visitorTypesLocationB: undefined,
    individualVisitorsLocationA: undefined,
    individualVisitorsLocationB: undefined,
    dwellTimesComplete: [],
    dwellTimesPerTime: {},
    dwellTimesPerDate: {}
};

export default state;
