import tabVisitorTypesState from "./tab/visitor-types/state";

const state = {
    id: "vpiDashboard",
    active: false,
    name: "translate#additional:modules.tools.vpiDashboard.title",
    icon: "bi-graph-up",
    renderToWindow: true,
    resizableWindow: true,
    isVisibleInMenu: true,
    deactivateGFI: false,
    frequencyData: undefined,
    chartData: "overview",
    allDataClicked: true,
    averageVisitorsPerMonth: [],
    averageVisitorsPerDay: [],
    individualVisitorsPerYear: "",
    allLocationsGeoJson: undefined,
    allLocationsArray: [],
    barChartDailyData: [],
    lineChartDailyData: [],
    barChartMonthlyData: [],
    lineChartMonthlyData: [],
    barChartData: [],
    lineChartData: [],
    showLoader: false,
    dwellTimeLocationA: undefined,
    dwellTimeLocationB: undefined,
    ageGroupsLocationA: undefined,
    ageGroupsLocationB: undefined,
    visitorTypesLocationA: undefined,
    visitorTypesLocationB: undefined,
    individualVisitorsLocationA: undefined,
    individualVisitorsLocationB: undefined,
    dwellTimesComplete: [],
    dwellTimesPerTime: {},
    dwellTimesPerDate: {},
    allAgeGroupsData: [],
    allAgeGroupsMonthlyData: [],
    allAgeGroupsMonthlyDataLine: [],
    ageGroupsYearlyData: [],
    ageGroupxLabels: [],
    allAgeGroupsYears: [],
    ageGroupPieChartLabels: ["20-29", "30-39", "40-49", "50-59", "60-69", ">69"],
    ...tabVisitorTypesState
};

export default state;
