<script>
import {mapGetters} from "vuex";
import utils from "../../utils";

export default {
    name: "ColorCodeLegend",
    components: {
    },
    props: {
        // statistical values of chosen data set
        results: {
            type: Array,
            default: () => []
        },
        // d3 colorScale to generate colors based on numerial values
        colorScale: {
            type: Object,
            default: () => ({})
        },
        // Helper to force vue to update dom
        updateLegendList: {
            type: Number,
            default: () => 0
        },
        // ConditionW
        dashboardOpen: {
            type: Boolean,
            default: () => false
        },
        selectedYear: {
            type: String,
            default: () => "2020"
        },
        yearSelector: {
            type: String,
            default: () => "2020"
        }
    },
    data () {
        return {
            // highest values in selected dataset
            hiVal: 0,
            // lowest values in selected dataset
            loVal: 0,
            // colorValues generated by colorScale prop
            legendColors: [],
            // fallback for selectedFeatures to remove wrong data
            matchResults: []
        };
    },
    computed: {
        ...mapGetters("Tools/DistrictSelector", ["selectedFeatures", "label", "keyOfAttrName", "keyOfAttrNameStats"]),
        backgroundGradient () {
            return "background: linear-gradient(90deg," + this.legendColors[0] + "," + this.legendColors[1] + "," + this.legendColors[2] + ")";
        }
    },
    watch: {
        updateLegendList () {
            this.generateDynamicLegend(this.results, this.colorScale);
        }
    },
    mounted () {
        this.generateDynamicLegend(this.results, this.colorScale);
    },
    methods: {
        /**
         * @todo todo
         * @description Generates dynamic Legend in CCM based on selected feature values.
         * @param {*} results Values calculated in renderVisualization() function.
         * @param {*} colorScale color range for values from getColorsByValues() function.
         * @returns {void}
         */
        generateDynamicLegend (results, colorScale) {
            if (results.length > 1 && !this.dashboardOpen) {
                this.matchResults = this.results.filter(x => {
                    return this.selectedFeatures.some(y => {
                        return utils.unifyString(x.getProperties()[this.keyOfAttrNameStats]) === utils.unifyString(y.getProperties()[this.keyOfAttrName]);
                    });
                });

                colorScale.legend.values.forEach((value, index) => {
                    if (value === "Keine Daten") {
                        colorScale.legend.colors.splice(index, 1);
                        colorScale.legend.values.splice(index, 1);
                    }
                });

                this.legendColors = [colorScale.scale(colorScale.legend.values[0]), colorScale.scale((colorScale.legend.values[colorScale.legend.values.length - 1] + colorScale.legend.values[0]) / 2), colorScale.scale(colorScale.legend.values[colorScale.legend.values.length - 1])];

                this.loVal = colorScale.legend.values[0].toLocaleString(this.currentLocale);
                this.hiVal = colorScale.legend.values[colorScale.legend.values.length - 1].toLocaleString(this.currentLocale);
            }
        },
        markerPosition (index) {
            const value = this.matchResults[index].getProperties()[this.yearSelector + this.selectedYear],
                relativeValue = ((value - this.colorScale.legend.values[0]) * 100) / (this.colorScale.legend.values[this.colorScale.legend.values.length - 1] - this.colorScale.legend.values[0]);

            if (index > this.matchResults.length) {
                return "display:none";
            }

            if (Math.round(relativeValue) === 100) {
                return "left: calc(" + Math.round(relativeValue) + "% - 8px);";
            }

            return "left: " + Math.round(relativeValue) + "%;";
        }
    }
};
</script>

<template lang="html">
    <div
        class="component_wrapper"
    >
        <div
            id="legend_wrapper"
            :key="updateLegendList"
            :style="backgroundGradient"
        >
            <div
                v-for="(feature, i) in matchResults"
                :key="feature.id"
                class="legend_mark"
                :style="markerPosition(i)"
            >
                <div class="mark_tip" />
                <div class="hoverbox">
                    <p class="district">
                        {{ matchResults[i].getProperties()[keyOfAttrNameStats] + ": " }}
                    </p>
                    <p class="value">
                        {{ matchResults[i].getProperties()[yearSelector + selectedYear] }}
                    </p>
                </div>
            </div>
        </div>
        <div class="top val">
            {{ hiVal }}
        </div>
        <div class="low val">
            {{ loVal }}
        </div>
    </div>
</template>

<style lang="scss">
    @import "../../utils/variables.scss";
    .component_wrapper {
        margin:10px auto;
        display:flex;
        flex-flow:row wrap;
        justify-content:center;

        .val {
            flex:0 0 10%;
            height:30px;
            line-height:30px;
            padding:0px 5px;
            font-size:80%;
            font-weight:700;
            border:1.5px solid #222;

            &.top {
                order:3;
            }

            &.low {
                order:1;
            }
        }

        #legend_wrapper {
            position:relative;
            flex:0 0 70%;
            height:0px;
            opacity:0;
            pointer-events:none;
            margin:0px auto;
            overflow:hidden;
            height:30px;
            opacity:1;
            pointer-events:all;
            overflow:visible;
            order:2;

            .legend_mark {
                position:absolute;
                width:10px;
                background:transparent;
                border-radius:1px;
                border:1px solid black !important;
                top:-5px;
                left:0;
                background:whitesmoke;
                //height:calc(100% + 2px);
                height:10px;
                z-index:10;
                @include drop_shadow();

                &:after {
                    content:'';
                    position:absolute;
                    width:1px;
                    height: 12px;
                    top: 15px;
                    left:50%;
                    transform: translateX(-50%);
                    background:rgba(255,255,255,0.8);
                }

                .mark_tip {
                    position:absolute;
                    top:100%;
                    left:-1px;
                    width:0;
                    height:0;
                    border-left: 5px solid transparent;
                    border-right: 5px solid transparent;
                    border-top: 5px solid black;
                    z-index:15;
                    @include drop_shadow();

                    &:after {
                        content: '';
                        width: 0;
                        height: 0;
                        border-left: 5px solid transparent;
                        border-right: 5px solid transparent;
                        border-top: 5px solid whitesmoke;
                        position: absolute;
                        z-index:18;
                        top: -6px;
                        left: -5px;
                    }
                }

                .hoverbox {
                    position:absolute;
                    left:50%;
                    bottom:calc(100% + 3px);
                    width:max-content;
                    height:30px;
                    padding:10px 20px;
                    opacity:0;
                    pointer-events:none;
                    box-sizing: border-box;
                    z-index:10;
                    @include paper_bg();
                    @include drop_shadow();

                    p {
                        display:inline;
                        color:#444;
                        font-size:120%;
                        font-weight:300;

                        &:first-child {
                            color:#222;
                            font-weight:500;
                        }
                    }
                }

                &:hover {
                    cursor:pointer;
                    .hoverbox {
                        opacity:1;
                        pointer-events:all;
                        transition:0.3s;
                    }
                }
            }
        }
    }
</style>


