<script>
import Tool from "../../../../src/modules/tools/Tool.vue";
import getComponent from "../../../../src/utils/getComponent";
import {mapGetters, mapActions, mapMutations} from "vuex";
import getters from "../store/gettersCosiFileImport";
import mutations from "../store/mutationsCosiFileImport";
// import ImportManager from "./ImportManager.vue";
// import EditLayer from "./EditLayer.vue";
import InlineSvg from "vue-inline-svg";

export default {
    name: "CosiFileImport",
    components: {
        Tool,
        // ImportManager,
        // EditLayer,
        InlineSvg
    },
    data () {
        return {
            dzIsDropHovering: false,
            storePath: this.$store.state.Tools.CosiFileImport,
            // available CRS
            availableCrs: [{crs: "EPSG:4326", name: "WGS84"}],
            // set addNewLayer true to change to upload view
            addNewLayer: true,
            // set imported true while adjustments are made to layer that is about to be implemented
            imported: false,
            // new layer obj for imported file
            newLayer: {},
            // seperate features (values) to use them in selects etc
            newLayerValues: [],
            // array that stores all int values of new layer
            preNumericalValues: [],
            // array that stores values selected by user that are passed to the layer property (for calculate ratio et al)
            numericalValues: [],
            // searchField property on the layer
            searchField: [],
            // mouseHoverField property on the layer
            mouseHoverField: [],
            // stores selected svg file
            svgFile: "",
            // helper to store paths to preimplemented svg files
            imgObj: {
                a: "./assets/svg/geo_pin_A.svg",
                b: "./assets/svg/geo_pin_B.svg",
                c: "./assets/svg/geo_pin_C.svg",
                d: "./assets/svg/geo_pin_D.svg",
                e: "./assets/svg/geo_pin_E.svg",
                f: "./assets/svg/geo_pin_F.svg",
                g: "./assets/svg/geo_pin_G.svg",
                h: "./assets/svg/geo_pin_H.svg",
                i: "./assets/svg/geo_pin_I.svg",
                j: "./assets/svg/geo_pin_J.svg",
                k: "./assets/svg/geo_pin_K.svg",
                l: "./assets/svg/geo_pin_L.svg"
            },
            // bool that checks if you have a mixed dataset with point and polygon data
            pointsandpolygons: false,
            // if you have mixed data set, this stores the point color only
            svgColor: "#E20B0D",
            // bool that checks if dataset already has an address property
            noAddress: false,
            // bool that checks if dataset contains property with key from addressData array
            noPreselectedData: false,
            addressData: ["adresse", "address", "street", "road", "straße", "strasse", "zip", "zipcode", "plz", "postleitzahl", "city", "town", "village", "stadt", "ort", "county", "country", "state", "Land", "Staat"],
            // preconstructed address to display for user
            preAddress: [],
            // actual address property for layer
            addressSetup: [],
            // Switch to open Popup Select Field
            addFilter: false,
            // properties provided for filter whitelist
            filterWhiteList: [],
            // check if user wants to define styling manually or not
            autoStyle: false,
            // value based on which styling is autogenerated
            autoStyleValue: "",
            menu: false
        };
    },
    computed: {
        ...mapGetters("Tools/CosiFileImport", Object.keys(getters)),
        ...mapGetters("Tools/FeaturesList", ["layerMapById"]),
        ...mapGetters("Map", ["layerIds", "layers", "map", "projectionCode"]),
        selectedFiletype: {
            get () {
                return this.storePath.selectedFiletype;
            },
            set (value) {
                this.setSelectedFiletype(value);
            }
        },
        currentCrs: {
            get () {
                return this.crs;
            },
            set (value) {
                this.setCrs(value);
            }
        },
        dropZoneAdditionalClass: function () {
            return this.dzIsDropHovering ? "dzReady" : "";
        },
        swatchStyle () {
            return {
                backgroundColor: this.svgColor,
                cursor: "pointer",
                height: "30px",
                width: "30px",
                borderRadius: this.menu ? "50%" : "4px",
                transition: "border-radius 200ms ease-in-out"
            };
        },

        console: () => console
    },
    watch: {
        imported () {
            if (!this.imported) {
                this.addNewLayer = true;
            }
        },
        // set all relevant properties on layer object when new file is imported
        newLayerInformation (newValue, oldValue) {
            if (newValue !== oldValue) {
                this.newLayerValues = [];
                this.preNumericalValues = [];
                this.numericalValues = [];
                this.preAddress = [];
                this.addressSetup = [];
                this.newLayer = newValue;
                this.svgFile = "geo_pin_D.svg";
                this.newLayer.style = {};
                this.newLayer.points = this.newLayer.features.some(feature => feature.getGeometry().getType() === "Point");
                this.newLayer.polygons = this.newLayer.features.some(feature => feature.getGeometry().getType() !== "Point");
                this.createFeatureIDs(this.newLayer.features);
                this.preCheckNumericalValues(this.newLayer.features);
                this.checkForAddress();
                this.imported = true;
                this.addNewLayer = false;

                Object.entries(newValue.features[0].getProperties()).forEach(pair => {
                    const [key, value] = pair;

                    if (key !== "geometry") {
                        this.newLayerValues.push({
                            key: key,
                            value: value
                        });
                    }
                });
            }
        },
        // set addressSetup to empty if there are no address keys to preselect
        noPreselectedData () {
            this.addressSetup = [];
        },
        // set svg property on layer if icon is selected
        svgFile () {
            this.newLayer.svg = this.svgFile;
        }
    },
    created () {
        this.$on("close", this.close);
    },
    mounted () {
        const namedProjections = this.$store.state.configJs.namedProjections;

        if (namedProjections) {
            namedProjections.reverse();
            this.availableCrs = namedProjections.map(proj => (
                {
                    crs: proj[0],
                    name: proj[1].substring(7).replace(/\s[+](.*)/, "")
                }
            ));
        }
    },
    methods: {
        ...mapActions("Tools/CosiFileImport", [
            "importKML",
            "passLayer",
            "deleteLayerFromTree",
            "setSelectedFiletype"
        ]),
        ...mapActions("Alerting", ["addSingleAlert", "cleanup"]),
        ...mapActions("Tools/FeaturesList", ["addVectorlayerToMapping", "removeVectorLayerFromMapping"]),
        ...mapMutations("Tools/CosiFileImport", Object.keys(mutations)),
        ...mapMutations("Tools/CalculateRatio", ["setFacilityMappingUpdate"]),
        onDZDragenter () {
            this.dzIsDropHovering = true;
        },
        onDZDragend () {
            this.dzIsDropHovering = false;
        },
        onDZMouseenter () {
            this.dzIsHovering = true;
        },
        onDZMouseleave () {
            this.dzIsHovering = false;
        },
        onInputChange (e) {
            if (e.target.files !== undefined) {
                this.addFile(e.target.files);
            }
        },
        onDrop (e) {
            this.dzIsDropHovering = false;
            if (e.dataTransfer.files !== undefined) {
                this.addFile(e.dataTransfer.files);
            }
        },
        addFile (files) {
            files.forEach(file => {
                const reader = new FileReader();

                reader.onload = f => {
                    const layerName = this.getLayerName(file.name),
                        checkSameLayer = this.importedFileNames.filter(importedFileName => {
                            return this.getLayerName(file.name) === this.getLayerName(importedFileName);
                        });

                    this.importKML({raw: f.target.result, checkSameLayer: checkSameLayer, layerName: layerName, filename: file.name, pointImages: this.pointImages, textColors: this.textColors, textSizes: this.textSizes});
                };

                reader.readAsText(file);
            });
        },
        /**
         * @description Pass layer to actions (store) and add it to layer tree.
         * @returns {void}
         */
        async addLayer () {
            const layerArray = this.importedLayers;

            this.newLayer.numericalValues = this.numericalValues;
            this.newLayer.addressField = this.addressSetup;
            this.newLayer.searchField = this.searchField;
            this.newLayer.mouseHoverField = this.mouseHoverField;
            this.newLayer.autoStyle = this.autoStyle;
            this.newLayer.autoStyleValue = this.autoStyleValue;
            this.newLayer.style.svg = this.svgColor;
            this.newLayer.filterWhiteList = [...new Set([...this.filterWhiteList, this.searchField, ...this.numericalValues.map(x => x.id)])];

            // eslint-disable-next-line one-var
            const model = await this.passLayer(this.newLayer);

            this.addVectorlayerToMapping(model.attributes);
            this.imported = false;
            this.addNewLayer = true;
            layerArray.push({name: this.newLayer.name, id: this.newLayer.id, filename: this.newLayer.filename, icon: this.newLayer.svg, type: this.newLayer.type, color: this.svgColor});
            this.setImportedLayers(layerArray);
        },
        /**
         * @description Create unique ids for all features for them to be identified in the masterportal filter.
         * @param {Array} features All features of the imported dataset.
         * @returns {void}
         */
        createFeatureIDs (features) {
            this.newLayer.featureIds = [];
            features.forEach((feature, index) => {
                const id = this.newLayer.id + "_" + index;

                feature.setId(id);
                feature.setProperties({"id": id});
                this.newLayer.featureIds.push(feature.id);
            });
        },
        /**
         * @description Create an array with all values from imported dataset that only contain ints.
         * @param {Array} features All features of the imported dataset.
         * @returns {void}
         */
        preCheckNumericalValues (features) {
            const values = features[0].getProperties();

            Object.entries(values).forEach(pair => {
                const [key, value] = pair;

                if (!isNaN(value) && value !== true && value !== false && value !== null) {
                    this.preNumericalValues.push({id: key, name: key, value: value});
                }
            });
        },
        /**
         * @description Check if imported dataset already contains an address key and if not, than if there are similiar keys like street, zip, city etc to preselect.
         * @returns {void}
         */
        checkForAddress () {
            const values = this.newLayer.features[0].getProperties();

            if (!("address" in values)) {
                this.noAddress = true;

                for (const key in values) {
                    if (this.addressData.includes(key.replace(/\s+/g, "").replace(/[^a-zA-Z ]/g, ""))) {
                        this.preAddress.push(key);
                    }
                    else {
                        this.noPreselectedData = true;
                    }
                }
            }
        },
        addFilterToWhiteList (event) {
            this.filterWhiteList.push(event);
            this.addFilter = false;
        },
        removeFilterFromWhiteList (i) {
            this.filterWhiteList.splice(i, 1);
        },
        /**
         * @description Set svg file from select.
         * @param {String} file Contains the name of the svg.
         * @returns {void}
         */
        setLayerSVG (file) {
            this.svgFile = file;
        },
        /**
         * @description Deletes layer from layerTree in actions (store).
         * @param {String} filename filename of the layer that is about to be removed.
         * @returns {void}
         */
        removeLayer (filename) {
            const layerModel = Radio.request("ModelList", "getModelByAttributes", {type: "layer", filename: filename}),
                layerMap = this.layerMapById(layerModel.get("id"));

            this.removeVectorLayerFromMapping(layerMap);
            this.deleteLayerFromTree(filename);
        },
        close () {
            this.setActive(false);
            const model = getComponent(this.id);

            if (model) {
                model.set("isActive", false);
            }
        },
        showAlert (content, category = "Info", cssClass = "info") {
            this.addSingleAlert({
                category: category,
                content: content,
                displayClass: cssClass
            });
        },
        showInfo (message) {
            this.showAlert(message);
        },
        openManual () {

        },
        /**
         * Getting the layer name from the file name without the postfix as file format
         * @param {String} fileName name of the file
         * @returns {String} Returns the layer name
         */
        getLayerName (fileName) {
            return fileName.substr(0, fileName.lastIndexOf("."));
        }
    }
};
</script>

<template lang="html">
    <Tool
        :title="$t('additional:modules.tools.cosiFileImport.title')"
        :icon="glyphicon"
        :active="active"
        :render-to-window="renderToWindow"
        :resizable-window="resizableWindow"
        :deactivate-gfi="deactivateGFI"
    >
        <template #toolBody>
            <div
                v-if="active && !imported && addNewLayer"
                id="tool-file-import"
                class="importer"
            >
                <button
                    class="info_button"
                    :title="$t('additional:modules.tools.cosi.chartGenerator.infoTooltip')"
                    @click="openManual()"
                >
                    <span class="glyphicon glyphicon-question-sign" />
                </button>
                <p
                    class="cta"
                    v-html="$t('additional:modules.tools.cosiFileImport.captions.introInfo')"
                />
                <p
                    class="cta"
                    v-html="$t('additional:modules.tools.cosiFileImport.captions.introFormats')"
                />
                <div
                    class="vh-center-outer-wrapper drop-area-fake"
                    :class="dropZoneAdditionalClass"
                >
                    <div
                        class="vh-center-inner-wrapper"
                    >
                        <p
                            class="caption"
                        >
                            {{ $t("additional:modules.tools.cosiFileImport.captions.dropzone") }}
                        </p>
                    </div>

                    <div
                        class="drop-area"
                        @drop.prevent="onDrop"
                        @dragover.prevent
                        @dragenter.prevent="onDZDragenter"
                        @dragleave="onDZDragend"
                        @mouseenter="onDZMouseenter"
                        @mouseleave="onDZMouseleave"
                    />
                </div>

                <div>
                    <label class="upload-button-wrapper">
                        <input
                            type="file"
                            @change="onInputChange"
                        >
                        {{ $t("additional:modules.tools.cosiFileImport.captions.browse") }}
                    </label>
                </div>
                <div class="h-seperator" />
                <v-row>
                    <v-col cols="12">
                        <p
                            class="caption"
                        >
                            {{ $t("additional:modules.tools.cosiFileImport.captions.selectCrs") }}
                        </p>
                        <v-select
                            v-model="currentCrs"
                            dense
                            :items="availableCrs"
                            item-text="name"
                            item-value="crs"
                        />
                    </v-col>
                </v-row>

                <div v-if="importedFileNames.length > 0">
                    <div class="h-seperator" />
                    <p class="cta">
                        <label class="successfullyImportedLabel">
                            {{ $t("additional:modules.tools.cosiFileImport.successfullyImportedLabel") }}
                        </label>
                        <ul>
                            <li
                                v-for="(filename, index) in importedFileNames"
                                :key="index"
                            >
                                {{ filename }}
                                <v-btn
                                    class="remove"
                                    @click="removeLayer(filename)"
                                >
                                    <v-icon>mdi-trash-can-outline</v-icon>
                                </v-btn>
                            </li>
                        </ul>
                    </p>
                </div>
            </div>
            <div
                v-if="active && !addNewLayer"
                id="cosi-layer-handler"
                class="handler"
                :class="{expand: importedLayers.length}"
            >
                <button
                    class="info_button"
                    :title="$t('additional:modules.tools.cosi.calculateRatio.infoTooltip')"
                    @click="showInfo()"
                >
                    <span class="glyphicon glyphicon-question-sign" />
                </button>
                <!--New Layer Handling-->
                <template v-if="imported">
                    <div class="wrapper">
                        <div class="head">
                            <p class="meta">
                                <strong>ID</strong> {{ newLayer.id }}
                            </p>
                            <v-text-field
                                v-model="newLayer.name"
                                label="Layername"
                                class="name"
                            />
                            <p class="info">
                                {{ $t("additional:modules.tools.cosiFileImport.createLayerInfo") }}
                            </p>
                        </div>
                        <div class="body">
                            <div class="wrapper">
                                <div class="features">
                                    <div
                                        class="feat_wrapper active style"
                                        @click="e => e.target.classList.toggle('active')"
                                    >
                                        <h3>{{ $t("additional:modules.tools.cosiFileImport.styling") }}</h3>
                                        <p class="featuresInfo">
                                            {{ $t("additional:modules.tools.cosiFileImport.featuresInfoStyling") }}
                                        </p>
                                        <div
                                            class="styling"
                                        >
                                            <div
                                                class="styling points"
                                            >
                                                <div
                                                    v-if="newLayer.points && !newLayer.polygons"
                                                    class="grp_wrapper btn"
                                                >
                                                    <div class="btn_grp">
                                                        <v-btn
                                                            v-for="svg, key in imgObj"
                                                            :key="key"
                                                            :class="{highlight: svgFile === 'geo_pin_' + key.toUpperCase() + '.svg'}"
                                                            @click="setLayerSVG('geo_pin_' + key.toUpperCase() + '.svg')"
                                                        >
                                                            <template v-if="svgFile === 'geo_pin_' + key.toUpperCase() + '.svg'">
                                                                <InlineSvg
                                                                    :src="imgObj[key]"
                                                                    :fill="svgColor"
                                                                />
                                                            </template>
                                                            <template v-else>
                                                                <InlineSvg
                                                                    :src="imgObj[key]"
                                                                    :fill="'#ffffff'"
                                                                />
                                                            </template>
                                                        </v-btn>
                                                    </div>
                                                </div>
                                                <div class="autostyle">
                                                    <div class="info_wrapper">
                                                        <v-checkbox
                                                            v-model="autoStyle"
                                                            label="Farbe nach Attributen"
                                                        />
                                                        <div
                                                            class="info_icon"
                                                            @click="showInfo($t('additional:modules.tools.cosiFileImport.autoStyleTooltip'))"
                                                        >
                                                            i
                                                        </div>
                                                    </div>
                                                </div>
                                                <div
                                                    v-if="autoStyle"
                                                    class="grp_wrapper"
                                                >
                                                    <v-select
                                                        v-model="autoStyleValue"
                                                        :items="newLayerValues"
                                                        label="Style-Feld auswählen"
                                                        title="Auswählen nach welchem Feld die Daten eingefärbt werden sollen"
                                                        item-value="key"
                                                        solo
                                                    >
                                                        <template
                                                            slot="selection"
                                                            slot-scope="data"
                                                        >
                                                            <span>{{ data.item.key }}</span>
                                                        </template>
                                                        <template
                                                            slot="item"
                                                            slot-scope="data"
                                                        >
                                                            <span><strong>{{ data.item.key }}</strong>: {{ data.item.value }}</span>
                                                        </template>
                                                    </v-select>
                                                </div>
                                            </div>
                                            <div
                                                v-if="autoStyle && autoStyleValue && isNaN(parseFloat(newLayer.features[0].get(autoStyleValue)))"
                                                class="grp_wrapper rainbow"
                                            >
                                                <p>
                                                    <strong>Regenbogenfarbspektrum</strong>
                                                </p>
                                                <div class="info_wrapper">
                                                    <v-checkbox
                                                        v-model="newLayer.rainbow"
                                                        label="Regenbogenfarbspektrum"
                                                        type="checkbox"
                                                    />
                                                    <div
                                                        class="info_icon"
                                                        @click="showInfo($t('additional:modules.tools.cosiFileImport.rainbowTooltip'))"
                                                    >
                                                        i
                                                    </div>
                                                </div>
                                            </div>
                                            <div
                                                v-if="!newLayer.rainbow"
                                                class="grp_wrapper"
                                            >
                                                <p class="featuresInfo">
                                                    <strong>Farbauswahl</strong>
                                                    {{ $t("additional:modules.tools.cosiFileImport.featuresInfoColor") }}
                                                </p>
                                                <v-text-field
                                                    v-model="svgColor"
                                                    hide-details
                                                    solo
                                                >
                                                    <template #append>
                                                        <v-menu
                                                            v-model="menu"
                                                            top
                                                            nudge-bottom="105"
                                                            nudge-left="16"
                                                            :close-on-content-click="false"
                                                        >
                                                            <template #activator="{ on }">
                                                                <div
                                                                    :style="swatchStyle"
                                                                    v-on="on"
                                                                />
                                                            </template>
                                                            <v-card>
                                                                <v-card-text class="pa-0">
                                                                    <v-color-picker
                                                                        ref="colorpicker"
                                                                        v-model="svgColor"
                                                                        dot-size="25"
                                                                        hide-inputs
                                                                        hide-mode-switch
                                                                        flat
                                                                    />
                                                                </v-card-text>
                                                            </v-card>
                                                        </v-menu>
                                                    </template>
                                                </v-text-field>
                                            </div>
                                        </div>
                                    </div>
                                    <div
                                        class="feat_wrapper facility"
                                        @click="e => e.target.classList.toggle('active')"
                                    >
                                        <h3>{{ $t("additional:modules.tools.cosiFileImport.facility") }}</h3>
                                        <p class="featuresInfo">
                                            {{ $t("additional:modules.tools.cosiFileImport.featuresInfoFilter") }}
                                        </p>
                                        <div class="type">
                                            <div class="info_wrapper">
                                                <v-select
                                                    v-model="mouseHoverField"
                                                    :items="newLayerValues"
                                                    label="Namens-Feld bestimmen"
                                                    item-value="key"
                                                >
                                                    <template
                                                        slot="selection"
                                                        slot-scope="data"
                                                    >
                                                        <span>{{ data.item.key }}</span>
                                                    </template>
                                                    <template
                                                        slot="item"
                                                        slot-scope="data"
                                                    >
                                                        <span><strong>{{ data.item.key }}</strong>: {{ data.item.value }}</span>
                                                    </template>
                                                </v-select>
                                                <div
                                                    class="info_icon"
                                                    @click="showInfo($t('additional:modules.tools.cosiFileImport.namensfeldTooltip'))"
                                                >
                                                    i
                                                </div>
                                            </div>
                                        </div>
                                        <div class="type">
                                            <div class="info_wrapper">
                                                <v-select
                                                    v-model="searchField"
                                                    :items="newLayerValues"
                                                    label="Typen-Feld bestimmen"
                                                    item-value="key"
                                                >
                                                    <template
                                                        slot="selection"
                                                        slot-scope="data"
                                                    >
                                                        <span>{{ data.item.key }}</span>
                                                    </template>
                                                    <template
                                                        slot="item"
                                                        slot-scope="data"
                                                    >
                                                        <span><strong>{{ data.item.key }}</strong>: {{ data.item.value }}</span>
                                                    </template>
                                                </v-select>
                                                <div
                                                    class="info_icon"
                                                    @click="showInfo($t('additional:modules.tools.cosiFileImport.typenfeldTooltip'))"
                                                >
                                                    i
                                                </div>
                                            </div>
                                        </div>
                                        <div
                                            v-if="noAddress"
                                            class="address"
                                            @click="e => e.target.classList.toggle('active')"
                                        >
                                            <h4>{{ $t("additional:modules.tools.cosiFileImport.address") }}</h4>
                                            <p>
                                                {{ $t("additional:modules.tools.cosiFileImport.featuresInfoAddress") }}
                                            </p>
                                            <template v-if="noPreselectedData">
                                                <h4>{{ $t("additional:modules.tools.cosiFileImport.preSelectedData") }}</h4>
                                                <p>{{ $t("additional:modules.tools.cosiFileImport.preSelectedDataFound") }}</p>
                                                <v-btn
                                                    class="viewall"
                                                    @click="noPreselectedData = false"
                                                >
                                                    {{ $t("additional:modules.tools.cosiFileImport.viewAllData") }}
                                                </v-btn>

                                                <ul class="address">
                                                    <li
                                                        v-for="(data, i) in preAddress"
                                                        :key="i"
                                                        class="vis"
                                                    >
                                                        <label><strong>{{ data }}</strong></label>
                                                        <input
                                                            v-model="addressSetup"
                                                            type="checkbox"
                                                            :value="data"
                                                        >
                                                    </li>
                                                </ul>
                                            </template>
                                            <template v-else>
                                                <ul class="address">
                                                    <li
                                                        v-for="(data, dataKey, i) in newLayer.features[0].values_"
                                                        :key="i"
                                                        :class="{ vis: dataKey !== 'geometry' && dataKey !== 'address' }"
                                                    >
                                                        <label><strong>{{ dataKey }}</strong></label>
                                                        <input
                                                            v-model="addressSetup"
                                                            type="checkbox"
                                                            :value="dataKey"
                                                        >
                                                    </li>
                                                </ul>
                                            </template>
                                            <div
                                                v-if="addressSetup.length"
                                                class="example"
                                            >
                                                <span
                                                    v-for="(string, index) in addressSetup"
                                                    :key="string"
                                                ><span v-if="index > 0">, </span>{{ newLayer.features[0].getProperties()[string] }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div
                                        class="feat_wrapper filterdata filter"
                                        @click="e => e.target.classList.toggle('active')"
                                    >
                                        <h3>{{ $t("additional:modules.tools.cosiFileImport.filter") }}</h3>
                                        <p class="featuresInfo">
                                            {{ $t("additional:modules.tools.cosiFileImport.filterInfo") }}
                                        </p>
                                        <ul v-if="filterWhiteList.length">
                                            <h4>{{ $t("additional:modules.tools.cosiFileImport.filterSelection") }}</h4>
                                            <li
                                                v-for="(set, i) in filterWhiteList"
                                                :key="i"
                                            >
                                                <p>{{ set }}</p>
                                                <v-btn
                                                    @click="removeFilterFromWhiteList(i)"
                                                >
                                                    <v-icon>mdi-close</v-icon>
                                                </v-btn>
                                            </li>
                                        </ul>
                                        <v-btn
                                            v-if="!addFilter"
                                            class="add"
                                            @click="addFilter = !addFilter"
                                        >
                                            <p>
                                                {{ $t("additional:modules.tools.cosiFileImport.addSetToFilter") }}
                                            </p>
                                            <v-icon>mdi-plus-thick</v-icon>
                                        </v-btn>
                                        <div
                                            v-if="addFilter"
                                            class="select_popup"
                                        >
                                            <v-select
                                                :items="newLayerValues.filter(x => !filterWhiteList.includes(x.key))"
                                                item-value="key"
                                                item-text="key"
                                                label="Objekteigenschaft auswählen"
                                                solo
                                                @input="addFilterToWhiteList"
                                            />
                                        </div>
                                    </div>
                                    <div
                                        class="feat_wrapper prenum"
                                        @click="e => e.target.classList.toggle('active')"
                                    >
                                        <h3>{{ $t("additional:modules.tools.cosiFileImport.preNum") }}</h3>
                                        <p class="featuresInfo">
                                            {{ $t("additional:modules.tools.cosiFileImport.featuresInfo") }}
                                        </p>
                                        <ul class="preNums">
                                            <li
                                                v-for="(data, i) in preNumericalValues"
                                                :key="i"
                                            >
                                                <v-text-field
                                                    v-model="data.name"
                                                    class="preNumName"
                                                    label="Name der Eigenschaft"
                                                />
                                                <label><strong>{{ data.id }}</strong> ({{ data.value }})</label>
                                                <input
                                                    v-model="numericalValues"
                                                    type="checkbox"
                                                    :value="data"
                                                >
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="submit">
                            <v-btn
                                class="cancel_btn"
                                @click="imported = false"
                            >
                                {{ $t("additional:modules.tools.cosiFileImport.cancel") }}
                            </v-btn>
                            <v-btn
                                class="submit_btn"
                                @click="addLayer"
                            >
                                {{ $t("additional:modules.tools.cosiFileImport.layerButton") }}
                            </v-btn>
                        </div>
                    </div>
                </template>
            </div>
        </template>
    </Tool>
</template>

<style lang="less" scoped>
    @import "~variables";
    @import "../../utils/variables.less";

    .h-seperator {
        margin:12px 0 12px 0;
        border: 1px solid #DDDDDD;
    }

    input[type="file"] {
        display: none;
    }
    input[type="button"] {
        display: none;
    }

    .upload-button-wrapper {
        border: 2px solid #DDDDDD;
        background-color:#FFFFFF;
        display: block;
        text-align:center;
        padding: 8px 12px;
        cursor: pointer;
        margin:12px 0 0 0;
        font-size: @font_size_big;
        transition: background 0.25s;

        &:hover {
            background-color:#EEEEEE;
        }
    }

    .cta {
        margin-bottom:12px;
        max-width:300px;
    }

    .drop-area-fake {
        background-color: #FFFFFF;
        border: 2px dashed @brightblue;
        padding:24px;
        transition: background 0.25s, border-color 0.25s;

        &.dzReady {
            background-color:@masterportal_blue;
            border-color:transparent;

            p.caption {
                color:#FFFFFF;
            }
        }

        p.caption {
            margin:0;
            text-align:center;
            transition: color 0.35s;
            font-family: @font_family_accent;
            font-size: @font_size_huge;
            color: @accent_disabled;
        }
    }
    .drop-area {
        position:absolute;
        top:0;
        left:0;
        right:0;
        bottom:0;
        z-index:10;
    }
    .vh-center-outer-wrapper {
        top:0;
        left:0;
        right:0;
        bottom:0;
        text-align:center;
        position:relative;

        &:before {
            content:'';
            display:inline-block;
            height:100%;
            vertical-align:middle;
            margin-right:-0.25em;
        }
    }
    .vh-center-inner-wrapper {
        text-align:left;
        display:inline-block;
        vertical-align:middle;
        position:relative;
    }

    .successfullyImportedLabel {
        font-weight: bold;
    }
    .introDrawTool {
        font-style: italic;
    }

    .handler {
        width:400px;

        .newLayerButton {
            position:absolute;
            top:5px;
            right:20px;
            background:@green;
            color:whitesmoke;
            min-width:0px;
            width:40px;
            height:30px;
            opacity:0.75;
        }

        /*&.expand {
            display:flex;
            flex-flow:row wrap;
            justify-content:flex-start;
            width:560px;

            .wrapper {
                flex:0 0 380px;
                margin:0;
            }

            .manager {
                flex:0 0 180px;
                margin:25px 0px;
                background:whitesmoke;
                box-shadow: inset 10px 0px 25px -16px rgba(0,0,0,0.75);
            }
        }*/

        .wrapper {
            .head {
                display:flex;
                flex-flow:row wrap;
                margin:10px 0px;
                padding-bottom:10px;
                border-bottom:1px solid #ccc;

                    p.meta {
                    flex-basis:100px;
                    height:40px;
                    line-height:40px;
                    background:#eee;
                    text-align:center;
                    margin-top:-10px;
                    margin-bottom:20px;
                    font-size:80%;

                    strong {
                        color:#000;
                    }
                }

                .name {
                    flex-basis:calc(100% - 120px);
                    flex-grow:0;
                    height:40px;
                    margin-left:5px;
                    margin-top:0;
                    padding:0;

                    ::v-deep .v-label--active {
                        left:1px !important;
                        font-size:80%;
                        color:@masterportal_blue;
                        transform-origin:center left;
                    }
                }

                .info {
                    margin:10px 0px;
                    background:#fafafa;
                    padding:20px;
                    box-sizing: border-box;
                    text-align:justify;
                }
            }
            .body {
                .wrapper {
                    .styling {
                        display:flex;
                        flex-flow:row wrap;
                        justify-content:space-between;
                        width:100%;
                        max-width:400px;

                        h3 {
                            flex:1 0 100%;
                            color:#aaa;
                            font-size:110%;
                            border:none;
                            line-height:normal;
                            margin-top: 20px;
                        }

                        .both {
                            flex:1 0 100%;
                        }

                        .grp_wrapper {
                            display:flex;
                            flex-flow:row wrap;
                            flex:0 0 300px;

                            &.btn {
                                flex:1 0 100%;
                                padding:0;
                                background:whitesmoke;
                            }

                            .btn_grp {
                                width:100%;
                                display:flex;
                                flex-flow:row wrap;
                                justify-content:space-between;
                                margin:5px 0px;
                                padding:5px 10px;
                                box-sizing: border-box;

                                .v-btn {
                                    position:relative;
                                    border-radius:0px;
                                    background:transparent;
                                    box-shadow:none;
                                    margin:2px 0px;
                                    max-width:60px;
                                    min-width:0px;

                                    &:hover {
                                        transform:scale(1.05);
                                        transition:0.3s;
                                    }

                                    &.active {
                                        //border:1px solid #222;
                                    }

                                    &:after {
                                        content:'';
                                        position:absolute;
                                        top:100%;
                                        left:50%;
                                        transform:translateX(-50%);
                                        width:40%;
                                        height:3px;
                                        border-radius:50%;
                                        box-shadow: none;
                                        background:rgba(0,0,0,0.5);
                                        filter:blur(3px);
                                    }
                                }
                            }

                            .v-color-picker {
                                ::v-deep .v-color-picker__hue {
                                    background: linear-gradient(90deg,red,#ff0 16.66%,#0f0 33.33%,#0ff 50%,#00f 66.66%,#f0f 83.33%,red);
                                }

                                ::v-deep .v-color-picker__dot {
                                    width:50px;
                                    height:50px;
                                    border-radius:0px;
                                    margin-right:10px;
                                }
                            }

                            &.rainbow {
                                .v-input {
                                    height:30px;
                                    margin:3px 0px;

                                    ::v-deep label {
                                        margin:0px 10px;
                                    }
                                }
                            }
                        }

                        &.sub {
                            padding-top:10px;
                            margin-top:10px;
                            border-top:1px solid #ccc;
                        }
                    }

                    .features {
                        margin:5px 0px;

                        .feat_wrapper {
                            width:100%;
                            height:60px;
                            margin:10px 0px;
                            overflow:hidden;

                            &:hover {
                                cursor:pointer;
                            }

                            .info_wrapper {
                                position:relative;
                                max-width:80%;

                                .info_icon {
                                        position:absolute;
                                        top:50%;
                                        left:calc(100% + 16px);
                                        transform:translateY(-50%);
                                        width:16px;
                                        height:16px;
                                        border:2px solid #888;
                                        border-radius:50px;
                                        color:#888;
                                        text-align:center;
                                        line-height:14px;
                                        font-size:12px;

                                        &:hover {
                                            cursor:pointer;
                                        }
                                }
                            }

                            h3 {
                                position:relative;
                                display:block;
                                height:60px;
                                line-height:60px;
                                font-size:110%;
                                color:#222;
                                background:#eee;
                                border-radius:5px;
                                margin:0;
                                border:1px solid #ccc;
                                padding-left:30px;
                                pointer-events:none;
                                box-shadow: 0px 5px 10px -5px rgb(0 0 0 / 25%);

                                &:before {
                                    content:'+';
                                    position:relative;
                                    margin-left:-20px;
                                    margin-right:20px;
                                    height:60px;
                                    line-height:60px;
                                    font-size:130%;
                                    color:#444;
                                }
                            }

                            .autostyle {
                                position:relative;
                                width:70%;
                                margin:20px 0px 10px 0px;

                                .v-input--checkbox {
                                    position:relative;
                                    height:36px;
                                    margin:0;
                                    border-bottom:1px solid #ccc;

                                    ::v-deep label {
                                        margin:0;
                                        margin-left:10px;
                                        margin-top:4px;
                                        line-height:24px;
                                    }
                                }
                            }

                            &.active {
                                background:transparent;
                                box-shadow:none;
                                height:auto;
                                padding:10px;
                                padding-bottom:20px;
                                border:1px solid #eee;
                                border-radius:5px;

                                &:hover {
                                    cursor:default;
                                }

                                h3 {
                                    width:calc(100% + 28px);
                                    height:auto;
                                    margin-left:-14px;
                                    margin-top:-10px;
                                    border:1px solid @masterportal_blue;
                                    border-bottom:none;
                                    background:@brightblue;
                                    color:whitesmoke;
                                    line-height: 30px;

                                    &:hover {
                                        cursor:pointer;
                                    }

                                    &:before {
                                        content:'-';
                                        height:30px;
                                        line-height:30px;
                                        font-size:110%;
                                        color:white;
                                    }
                                }

                                h4 {
                                    font-size:120%;
                                    font-weight:900;
                                }

                                .viewall {
                                    display:block;
                                    font-size:100%;
                                    font-weight:900;
                                    border-radius:0px;
                                    text-transform: none;
                                    box-shadow:none;
                                    margin:5px 0px 5px auto;
                                }

                                .example {
                                    padding:5px 10px;
                                    background:#eee;
                                    opacity:0.75;
                                    font-style: italic;
                                }

                                .featuresInfo {
                                    flex-basis:100%;
                                    margin: 20px 0px;
                                    padding: 20px 5px 0px 5px;
                                    color:#888;
                                    font-size:100%;

                                    strong {
                                        display:block;
                                        margin-bottom:10px;
                                        color:#222;
                                    }
                                }

                                ul.address {
                                    border-top:1px solid #ccc;
                                    border-bottom:1px solid #ccc;
                                    padding:10px 0px;
                                    margin-top:10px;

                                    li {
                                        display:none;
                                        flex-flow:row wrap;
                                        height:30px;
                                        margin:5px 0px;
                                        background:#eee;

                                        label {
                                            max-width:calc(100% - 54px);
                                            margin:0px 10px;
                                            height:30px;
                                            line-height:30px;
                                            padding-left:10px;
                                            overflow:hidden;
                                        }

                                        input {
                                            margin:3px 10px 3px auto;
                                            width:24px;
                                            height:24px;
                                        }

                                        &.vis {
                                            display:flex;
                                        }
                                    }
                                }

                                ul.preNums {
                                    list-style:none;
                                    li {
                                        flex:1 0 100%;
                                        display:flex;
                                        flex-flow:row wrap;
                                        justify-content:flex-start;
                                        align-items:center;
                                        background:whitesmoke;
                                        margin:3px 0px;
                                        padding:0px 20px;
                                        box-sizing: border-box;

                                        .preNumName {
                                            flex:0 0 120px;
                                            margin-right:5px;
                                            font-size:100%;
                                            padding-top:5px;
                                            color:#000;

                                            ::v-deep .v-label--active {
                                                display:none;
                                                left:1px !important;
                                                color:@masterportal_blue;
                                                transform-origin:center left;
                                            }

                                            ::v-deep .v-input__slot {
                                                margin:0;

                                                input {
                                                    padding:2px 0px;
                                                }
                                            }


                                        }

                                        label {
                                            margin:0px 10px;
                                            border-left:2px solid #222;
                                            padding-left:10px;
                                        }

                                        input {
                                            margin:0 0 0 auto;
                                            width:24px;
                                            height:24px;
                                        }
                                    }
                                }
                            }

                            .v-text-field {
                                ::v-deep .v-label--active {
                                    transform-origin:top left;
                                }
                            }

                            &.filterdata {
                                position:relative;
                                margin:10px 0;

                                .add {
                                    width:100%;
                                    text-transform: none;
                                    font-size:100%;
                                    background:whitesmoke;

                                    p {
                                        display:inline;
                                        text-align:left;
                                    }

                                    .v-icon {
                                        color:@green;
                                        display:inline-block;
                                        margin:0 0 0 auto;
                                    }
                                }

                                .select_popup {
                                    width:100%;
                                    height:100%;
                                    margin:5px 0px;
                                }

                                ul {
                                    display:flex;
                                    flex-flow:row wrap;

                                    li {
                                        display:flex;
                                        flex:1 0 100%;
                                        height:40px;
                                        line-height:40px;
                                        flex-flow:row wrap;
                                        margin:1px 0px;
                                        background:#fafafa;

                                        p {
                                            flex-basis:calc(100% - 60px);
                                            flex-grow:1;
                                            line-height:40px;
                                            padding-left:10px;
                                            color:#222;
                                            font-weight:bold;
                                        }

                                        .v-btn {
                                            flex-basis:30px;
                                            min-width:0px;
                                            margin-right:5px;
                                            background:transparent;
                                            border-radius:0px;
                                            box-shadow:none;

                                            .v-icon {
                                                color:@masterportal_red;
                                                opacity:0.5;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            .submit {
                display:flex;
                flex-flow:row wrap;
                justify-content: flex-end;
                margin:10px 0px;
                padding-top:10px;
                border-top:1px solid #ccc;

                .cancel_btn {
                    display:block;
                    margin-right:3px;
                    border-radius:0px;
                    background:@masterportal_red;
                    color:white;
                    box-shadow:none;
                    opacity:0.75;
                }

                .submit_btn {
                    display:block;
                    border-radius:0px;
                    background:@masterportal_blue;
                    color:white;
                    box-shadow:none;
                }
            }
        }
    }

    .v-btn.remove {
        margin-left:5px;
        height:24px;
        width:24px;
        min-width:0;
        padding:0;
        font-size:16px;
        border-radius:3px;
        box-shadow:none;
        color:white;
        background:@masterportal_red;
        opacity:0.5;

        .v-icon {
            font-size:14px;
        }
    }

    .auto {
        .styling {
            padding:20px 0px;
            border-bottom:1px solid #ccc;

            .grp_wrapper {
                padding:10px 0px;
                flex-flow:row wrap;

                .info {
                    flex: 1 0 100%;
                }

                .v-select {
                    flex:1 0 100%;
                    margin:10px 0px;
                }

                .v-btn {
                    &.highlight {
                        background-color:@masterportal_blue !important;
                    }
                }

                .v-color-picker {
                    flex:1 0 100%;

                    ::v-deep .v-color-picker__hue {
                        border-radius:0px;
                        margin-bottom:0px;
                        background: linear-gradient(90deg,red,#ff0 16.66%,#0f0 33.33%,#0ff 50%,#00f 66.66%,#f0f 83.33%,red);
                    }

                    ::v-deep .v-color-picker__dot {
                        width:10px;
                        height:10px;
                        border-radius:0px;
                        margin-right:10px;
                    }

                    ::v-deep .v-color-picker__alpha {
                        display:none;
                    }
                }
            }
        }
    }

    .style_select {
        width:100%;
        height:30px;
        display:flex;
        flex-flow:row wrap;
        border-bottom:1px solid #aaa;

        .selector {
            flex-basis:auto;
            background:whitesmoke;
            color:#666;
            padding:5px 10px;
            margin-right:2px;

            &:hover {
                cursor:pointer;
            }

            &.highlight {
                background:white;
                border-top:1px solid #aaa;
                border-right:1px solid #aaa;
                border-left:1px solid #aaa;
                border-bottom:1px solid white;
                color:#222;
                margin-bottom:-1px;
            }
        }
    }
</style>
